# Classic Load Balancer (CLB) Default Configuration
# This file defines the default rendering settings for Classic ELB instances

# Display settings - what information to show
display:
  show_scheme: true  # internet-facing or internal
  show_listeners: true
  show_availability_zones: false
  show_health_checks: true
  show_security_groups: false
  show_instances: true
  show_cross_zone_balancing: false
  show_connection_draining: false

# Label formatting
label:
  # Available variables: {name}, {dns_name}, {scheme}, {vpc_id}
  primary_format: "{name}"
  secondary_format: "{scheme}"
  tertiary_format: ""  # Optional third line
  max_label_length: 50
  truncate_style: "ellipsis"

# Visual settings
visual:
  icon_style: "classic"  # "classic", "generic"
  icon_size: "medium"
  show_status_indicator: false  # Classic ELBs don't have complex states

# Clustering and grouping
clustering:
  group_by: "scheme"  # "scheme", "vpc", "availability_zone", "none"
  cluster_label_format: "{scheme} Classic Load Balancers"
  show_cluster_border: true
  cluster_style: "dashed"

# Connection settings
connections:
  show_instance_connections: true
  show_listener_details: true
  connection_label_format: "{port}/{protocol}"
  health_check_label_format: "HC: {port}{path}"
  
# Filtering rules
filters:
  exclude_schemes: []  # "internet-facing", "internal"
  include_only_schemes: []
  exclude_protocols: []  # "HTTP", "HTTPS", "TCP", "SSL"
  min_instance_count: null
  max_instance_count: null

# Health check settings
health_checks:
  show_interval: false
  show_timeout: false
  show_unhealthy_threshold: false
  show_healthy_threshold: false